### ISSUE TITLE
TODO: Implement websocket client

### ISSUE THREAD

**Issue by tsvilans** [speckleworks/PySpeckle#1]
Implement websocket client for sending / receiving updates from the server.

- `websockets` with `asyncio` seems to be a good way to go
- This has been tested in a script, so it just needs some thought about how to integrate it into the SpeckleApiClient

**Comment by AntoineDao** [comment]
Implemented an initial version of this in #15. It essentially generates a [websocket-client](https://github.com/websocket-client/websocket-client) class instance.

Here's an example implementation:
```python
from speckle import SpeckleApiClient

host = 'hestia.speckle.works'
stream_id = 'MawOwhxET'

client = SpeckleApiClient(host=host)
client.login('test@test.com', 'testestestest')

def print_message(ws, message):
    print(message)


ws = client.websockets(stream_id, on_message=print_message)

# Send a message to the stream
ws.send('Hi Speckle!!!')

# Start a listening server that will print what ever message
# is sent to it (due to the print_message function defined above)
ws.run_forever()
```
