### ISSUE TITLE
Can't add user

### ISSUE THREAD

**Issue by grootstebozewolf** [speckleworks/PySpeckle#16]
When I create an account in SpecleBlender it raised an [error](https://github.com/speckleworks/SpeckleBlender/issues/10).

After fixing this error the user still did not add, presumably due to an issue with either PySpeckle or the hestia server.

As of this writing tried this a minute ago and got this response:
https://hestia.speckle.works/api/v1
Failed to login to server 'https://hestia.speckle.works/api/v1' with email '....'

**Comment by tsvilans** [comment]
Fixed. 

`ClientBase` does not return any value to say if it succeeded or failed on login. Relies on `assert` instead. `SpeckleBlender` expected a yay or nay.
