### ISSUE TITLE
TODO: More API calls: Comments

### ISSUE THREAD

**Issue by tsvilans** [speckleworks/PySpeckle#2]
The Comment API calls need to be implemented. The code can easily be recycled from other API calls.

- CommentCreateAsync
- CommentDeleteAsync
- CommentGetAsync
- CommentGetFromResourceAsync
- CommentUpdateSync

**Comment by AntoineDao** [comment]
Are we good to close this now that it's implemented and tested in #11 ?

**Comment by AntoineDao** [comment]
I'm going to go with yes this is resolved.
