### ISSUE TITLE
API response should not be printed all the time

### ISSUE THREAD

**Issue by htlcnn** [speckleworks/PySpeckle#26]
https://github.com/speckleworks/PySpeckle/blob/22c9cbf7049848484ac6e2a0542129d8b00e8062/speckle/base/resource.py#L127
For large stream, json responses would be quite big. Printing them would take long time. We don't have to print response every time we need to get one.

**Comment by didimitrie** [comment]
I guess that's a debugging leftover. Feel free to submit a PR, & ping @tsvilans / @izzylys / @AntoineDao, the custodians of this repo :)
