### ISSUE TITLE
Tests failing because the speckleserver docker image no longer has `latest` tag

### ISSUE THREAD

**Issue by AntoineDao** [speckleworks/PySpeckle#28]
Tests are failing because the [speckleserver image](https://hub.docker.com/r/speckle/speckleserver/tags) no longer has the `latest` tag for some reason.

Will also raise an issue on speckleserver repo.

**Comment by didimitrie** [comment]
I removed the `latest` tag as it was kind-of deprecated when we (you! 😅) switched to tagged docker images; got feedback from people pulling the latest image, which was 6 months old  at the time. 

Not sure wether we need to add it back (for the sake of consistency & conscious server upgrades would not?).

**Comment by AntoineDao** [comment]
Every time...

![image](https://user-images.githubusercontent.com/20436635/76803345-52c5e100-6825-11ea-8217-f67e4d704903.png)

I'll patch a fix to the server...

**Comment by AntoineDao** [comment]
Manually pushed a `latest` image to docker hub and pushed PR to speckleserver. Tests are now running as expected.
