### ISSUE TITLE
TODO: Make API calls asynchronous

### ISSUE THREAD

**Issue by tsvilans** [speckleworks/PySpeckle#5]
Stop lying in the code and actually make all those Async API calls asynchronous, probably with `asyncio`.

**Comment by AntoineDao** [comment]
Out of curiousity, why are we wanting to make this asynchronous? Is the idea to use the python client in a webserver or for heavy duty automation?

**Comment by tsvilans** [comment]
> Out of curiousity, why are we wanting to make this asynchronous? Is the idea to use the python client in a webserver or for heavy duty automation?

Simply because the .NET client was doing it ;) I'll close this until there is a clear need for it.

**Comment by didimitrie** [comment]
FYI, and AFAIK, the python client is used for some nifty automation inside a corporation you might heave heard of. </ offtopic>

**Comment by AntoineDao** [comment]
Maybe members of said corporation could contribute to said client if/when they need async calls :stuck_out_tongue:
